mlflow:
    index_exp_name: "pdf_indexing"
    retrieval_exp_name: "pdf_rag"
embedding:
  model_name: "BAAI/bge-large-en-v1.5"
vector_store:
  collection_name: "pdf_documents"
  embedding_dim: 1024
offline:
  chunking:
    chunk_size: 500
    chunk_overlap: 100
    separators:
      - "\n\n"
      - "\n"
      - " "

