mlflow:
    index_exp_name: "pdf_indexing"
    retrieval_exp_name: "pdf_rag"
embedding:
  model_name: "BAAI/bge-large-en-v1.5"
vector_store:
  collection_name: "pdf_documents"
  embedding_dim: 1024
chunking:
  chunk_size: 500
  chunk_overlap: 100
  separators:
    - "\n\n"
    - "\n"
    - " "
llm:
  model: "llama-3.3-70b-versatile"
  temperature: 0
  max_tokens: 2000

llm_judge:
  model: "gemma2:2b"
  temperature: 0
  max_tokens: 2000
